apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-model-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Abdulrahman-Mansor/Email_Body_DL_Phishing_Detection.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: model-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
