name: Test docker image
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: build main.py
        run: |
          python build main.py

      - name: Download model files
        run: |
          chmod +x downloadModel.sh
          ./downloadModel.sh

      - name: Run compose up
        run: |
          docker compose up -d --wait
          docker images
